# -*- coding: utf-8 -*-
"""assignment-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwRodZwPF_nvzFWWG7nGqlcsMCjAk9fX
"""

List=["neelu","nidhi","amitht"]
print(List)

from typing import Concatenate
List1=[28,"nidhi",6,78,"arr"]
List2=[4,5,6,7,8]
Concatenate=List1 + List2
print(Concatenate)

t=['r','y','u']
t[:1]

marks=[45,67,89]
age=[12,17,18]
hours=[4,8,10]

my_list=[1,'hello',2.23]
print("Original List:",my_list)
my_list.append('world')
print("List after appending 'world':", my_list)
my_list.remove(2.23)
print("List after removing 3.14:",my_list)

my_tuple=(91,'apple',3.14)
print("Original Tuple:",my_tuple)
print("First element:",my_tuple[0])

for i in range(1,6):
  print(i)

i=1
while i<=5:
  print(i)
  i+=1

num=int(input("Enter a number: "))
if num>=0:
  print("positive number")
else:
  print("negative number")

def greet(name):
  print(f"Hello from function, {name}!")
greet("nidhi")

print(dir(str))

a='Hello World'
b=a.upper()
print(b)

a='Hello World'
b=a.lower()
print(b)

a='hello World'
b=a.title()
print(b)

a='hello world'
b=a.replace('hello','hi')
print(b)

a='1234'
b=a.isdigit()
print(b)

a=range(10)
b=list(a)
print(b)

#start,stop then steps
a=range(1,10,2)
b=list(a)
print(b)

def add_numbers(a,b):
  return a+b
result=add_numbers(5,3)
print(result)

def greet(name, greeting="Hello"):
  print(f"{greeting}, {name}!")

def calculate_sum(*args):
  total=sum(args)
  return total

print("Sum of 1,2,3:", calculate_sum(1,2,3))
print("Sum of 1,2,3:", calculate_sum(1,2,3))

correct_username='admin'
correct_password='123'
while True:
  username=input("Enter your username: ")
  password=input("Enter your password: ")
  if username==correct_username and password==correct_password:
    print("Login successful!")
    break
  else:
      print("Invalid username or password. Please try again.")

a='nidhi' # method
b=a.capitalize()
print(b)

a=[2,4,5,6,7,8]  # built-in function
b=len(a)
print(b)

def name(): # userdefined
  name("nidhi")
print(name)

"""                                ASSIGNMENT"""

# Assignment#


def sum_of_even_numbers(n):
    total = 0
    for i in range(2, n + 1, 2):  # Start from 2 and increment by 2 to get even numbers
        total += i
    return total

# Input from the user
n = int(input("Enter a positive integer: "))
if n > 0:
    print(f"The sum of all even numbers between 1 and {n} is: {sum_of_even_numbers(n)}")
else:
    print("Please enter a positive integer.")