# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwRodZwPF_nvzFWWG7nGqlcsMCjAk9fX
"""

List=["neelu","nidhi","amitht"]
print(List)

from typing import Concatenate
List1=[28,"nidhi",6,78,"arr"]
List2=[4,5,6,7,8]
Concatenate=List1 + List2
print(Concatenate)

t=['r','y','u']
t[:1]

marks=[45,67,89]
age=[12,17,18]
hours=[4,8,10]

